Update patch set 1
Patch Set 1:

external/stlport/stlport/stl/_cstdio.h:97:26: error: no member named 'gets' in the global namespace

i guess that`s error from build environment but couldn't get what is missing

Patch-set: 1
Reviewer: Atul Bansode <15780@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Code-Review=0